plugins {
    id 'com.android.application'
}

android {
    namespace 'com.media.downloader'
    compileSdk 35

    defaultConfig {
        applicationId "com.media.downloader"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "5.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    androidResources {
        noCompress 'html'
    }

}

dependencies {
    implementation 'dev.ffmpegkit-maintained:yt-dlp-android:2.0.2'
}
